name: Lint

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  Lint:
    name: Lint
    uses: StirlingLabs/Actions/.github/workflows/lint.yaml@main
    with:
      defaultBranch: 'main'
      language: 'actions'
      include: '.+\.ya?ml'